#!/bin/sh
export LC_ALL=C
cd "$(dirname "$0")"
config_process_projects_cli=yes
. scripts/core-config || exit 1

hook_or_die "$config_build_pre" build-pre

for p in $config_projects; do
    highlight_msg "($config_projects) building $p"
    scripts/${p}-config     || err_msg_die "failed to configure '$p'"
    scripts/${p}-build "$@" || err_msg_die "failed to build '$p'"
done

hook_or_die "$config_build_post" build-post
success_msg "built: $config_projects"
