#!/bin/sh
export LC_ALL=C
cd "$(dirname "$0")"
config_process_projects_cli=yes
. scripts/core-config || exit 1

hook_or_die "$config_clean_pre" clean-pre

for p in $config_projects; do
    highlight_msg "($config_projects) cleaning $p"
    scripts/${p}-clean || err_msg_die "failed to clean '$p'"
done
rm -rf "$config_local_prefix"

hook_or_die "$config_clean_post" clean-post
success_msg "cleaned: $config_projects"
