#!/bin/sh
export LC_ALL=C
cd "$(dirname "$0")"
config_process_projects_cli=yes
. scripts/core-config || exit 1

# NOTE: path arguments must be absolute (unless you know what you're doing).
# This is because $(pwd) while the arguments are applied depends on the install
# script, and can change if the install script changes. Some install scripts
# cd to the source dir, others to a build dir, etc.

set -e
proj=$config_main

highlight_msg "Installing $proj"
scripts/${proj}-install "$@" || err_msg_die "failed to install $proj"
success_msg "installed: $proj"
