#!/bin/sh
export LC_ALL=C
cd "$(dirname "$0")"
config_process_projects_cli=yes
. scripts/core-config || exit 1

# Path arguments must be absolute. See note at ./install

set -e
proj=$config_main

highlight_msg "Uninstalling $proj"
scripts/${proj}-uninstall "$@" || err_msg_die "failed to uninstall $proj"
success_msg "uninstalled: $proj"
