#!/bin/sh
export LC_ALL=C

if [ x"${1:-}" != x"--skip-selfupdate" ]; then
    # try self-update of this repo (don't abort on failure) and re-run.
    (set -ex && cd "$(dirname "$0")" && git pull -r) || echo "Warning: cannot self-update"
    exec "$0" --skip-selfupdate "$@"
fi
shift

cd "$(dirname "$0")"
config_process_projects_cli=yes
. scripts/core-config || exit 1

# $1: tag prefix
versort_with_prefix() {
    # Emulate sort -V using a known prefix. Filter out anything else.
    sed -n -e "s/^$1\([0-9]\)/\\1/p" |\
        sort -n -t . -k 1,1 -k 2,2 -k 3,3 -k 4,4 |\
        sed -e "s/^/$1/"
    # GNU version of the same:
    # grep "^$2[0-9]" | sort -V
}

# $1: tag prefix
highest_release_tag() {
    local tag="$(git tag | grep -v rc | grep -v dev | versort_with_prefix "$1" | tail -n 1)"
    [ $? = 0 ] && [ "$tag" ] || err_msg_die "cannot find release tags with prefix '$1'"
    printf %s "$tag"
}

# $1: repo dir, 2: update value to perform at the repo, $3: release prefix
update_source_or_die() { (
    set -ex
    cd "$1"
    case "$2" in
         rebase) git pull --rebase;;
         master) git fetch && git checkout origin/master;;
        release) git fetch --tags && git checkout "refs/tags/$(highest_release_tag "$3")";;
             @*) git fetch --tags && git checkout "${2#@}";;
              *) err_msg_die "Unknown update type '$2'"
    esac
) || err_msg_die "update failed"; }

hook_or_die "$config_update_pre" update-pre

for p in $config_projects; do
    url="$(var_val config_${p}_git)"
    dir="$(var_val config_${p}_source)"
    update="$(var_val config_${p}_update)"
    rel_prfx="$(var_val config_${p}_release_prefix)"

    highlight_msg "($config_projects) updating $p/$update"
    [ -e "$dir" ] || git clone "$url" "$dir" || err_msg_die "cannot clone '$url' to '$dir'"
    [ "$update" = "none" ] || update_source_or_die "$dir" "$update" "$rel_prfx"

    hook_or_die "$(var_val config_${p}_update_post)" ${p}-update-post
done

scripts/debian-update-versions || err_msg_die "cannnot update debian versions"

hook_or_die "$config_update_post" update-post
success_msg "updated: $config_projects"
