#!/bin/sh
set -e

cd "$config_crossc_source"
make install-static prefix="$config_local_prefix" "$@"

# crossc.pc file has "Libs: ... -lstdc++" when built as static, so no special
# mpv configure options are required to handle the static linkage.
