#!/bin/sh
set -e

BUILD="$(pwd)"

USER_OPTS="$@"
OPTIONS="--enable-gpl --disable-debug --disable-doc"

if "$BUILD"/scripts/test-libmpv ; then
    OPTIONS="$OPTIONS --enable-pic"
fi
if [ "$config_build_host" ]; then
    OPTIONS="$OPTIONS --cross-prefix=$config_build_host-"
fi

OPTIONS="$OPTIONS $USER_OPTS"

# Do FFmpeg's job.
if ! ( echo "$OPTIONS" | grep -q -e --enable-openssl ) &&
   ! ( echo "$OPTIONS" | grep -q -e --enable-gnutls ) ;
then
    if pkg-config gnutls ; then
        OPTIONS="$OPTIONS --enable-gnutls"
        echo "Auto-enabling GnuTLS."
    elif pkg-config openssl ; then
        OPTIONS="$OPTIONS --enable-nonfree --enable-openssl"
        echo "Auto-enabling OpenSSL (creates a non-redistributable binary)."
    fi
fi

echo Using ffmpeg options: $OPTIONS

mkdir -p "$config_local_prefix"/tmp/ffmpeg_build
cd "$config_local_prefix"/tmp/ffmpeg_build
"$config_ffmpeg_source"/configure --prefix="$config_local_prefix" --enable-static --disable-shared $OPTIONS
