#!/bin/sh
set -e

# to generate a freertye2.pc for windows with cmake:
# - before 3aaae716b (post 2.10.1): -DUNIX:BOOL=true
# - 3aaae716b .. before 66005cbae (pre 2.11.0): like above AND scripts/freetype2-1-mingw.pc.patch
#   (and non-shallow clone, or else it won't succeed to apply)
# - since 66005cbae: no need to define UNIX and no need for a patch.

OPTIONS="
-DFT_DISABLE_HARFBUZZ=TRUE
-DFT_DISABLE_PNG=TRUE
-DFT_DISABLE_BROTLI=TRUE
"

if [ "$config_build_pic" = yes ]; then
    # untested, see https://stackoverflow.com/questions/38296756/what-is-the-idiomatic-way-in-cmake-to-add-the-fpic-compiler-option
    OPTIONS="$OPTIONS -DCMAKE_POSITION_INDEPENDENT_CODE=ON"
fi
if [ "$config_build_host" ]; then
    # cross is handled from the host-specific "cmake" which is setup globally
    true
fi

GEN_IS_VS=
if cmake --system-information | grep 'CMAKE_GENERATOR "' | grep -qi 'visual studio'; then
    # on msys[2] cmake might default to visual studio - not good for us, so we
    # override it later with -G"MSYS Makefiles"
    GEN_IS_VS=yes
fi

set -x
mkdir -p "$config_local_prefix"/tmp/freetype2_build
cd "$config_local_prefix"/tmp/freetype2_build
cmake ${GEN_IS_VS:+"-GMSYS Makefiles"} \
      -DCMAKE_INSTALL_PREFIX="$config_local_prefix" \
      -DLIB_INSTALL_DIR="$config_local_prefix"/lib \
      $OPTIONS "$@" "$config_freetype2_source"
