#!/bin/sh
set -e
OPTIONS=""

if [ "$config_build_pic" = yes ]; then
    OPTIONS="$OPTIONS --with-pic"
fi
if [ "$config_build_host" ]; then
    OPTIONS="$OPTIONS --host=$config_build_host"
fi

cd "$config_fribidi_source"
./bootstrap
./configure --prefix="$config_local_prefix" --libdir="$config_local_prefix/lib" --enable-static --disable-shared --without-glib $OPTIONS "$@"
