#!/bin/sh
set -e

OPTIONS=

if [ "$config_build_host" ]; then
    OPTIONS="$OPTIONS TARGET=$config_build_host"
fi

set -x

cd "$config_mpv_source"
exec meson setup build -Dbuildtype=release $OPTIONS "$@"
