#!/bin/sh
set -e

OPTIONS=
if [ "$config_build_host" ]; then
    OPTIONS="$OPTIONS TARGET=$config_build_host"
fi

echo Using mpv options: $OPTIONS "$@"

cd "$config_mpv_source"
./waf configure $OPTIONS "$@"
