#!/bin/sh
set -e

OPTIONS=
if [ "$config_build_pic" = yes ]; then
    OPTIONS="$OPTIONS XCFLAGS=-fPIC"
fi
if [ "$config_build_host" ]; then
    OPTIONS="$OPTIONS CC=$config_build_host-gcc"
fi

set -x
cd "$config_mujs_source"
make prefix="$config_local_prefix" install  $OPTIONS "$@"
